name: iTunes CI
on:
  pull_request:
    branches:
      - master
      - develop

jobs: 
  build:
    name: Build
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn 

      - name: Lint
        run: yarn lint:ci

      - name: Test
        run: yarn test

      - name: Accessibility tests using Storybook
        run: yarn test-storybook:ci

      - name: Build
        run: yarn build:prod

      - name: LHCI benchmark
        run: yarn lhci
