name: Continuous Deployment on PR
# 1
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - feat/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env: #2
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PATHS: '/*'
      AWS_S3_BUCKET: ${{ secrets.S3_UAT_BUCKET }}

    steps:
      - uses: actions/checkout@v2 #1

      - name: Get branch name #2
        id: vars
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies #3
        run: yarn

      - name: Build # 4
        run: export BRANCH_NAME=${{ steps.vars.outputs.branch }} && yarn build:uat

      - name: AWS Deploy #5
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: './build/'
          DEST_DIR: ${{steps.vars.outputs.branch}}

      - name: List UAT branches in fallback page
        run: yarn ls-uat-branches
        
      - name: Deploy S3 fallback page
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --exclude 'tests/*'
        env:
          SOURCE_DIR: './uat/'
          DEST_DIR: ''